name: save_me
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  go_router: ^14.1.2
  hexcolor: ^3.0.1
  intl: ^0.19.0
  june: ^1.0.0+1
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/kompasimg.png
    - assets/images/kompasicon.png
    - assets/images/verified.png
    - assets/images/webinar.png
    - assets/images/reporting.png
    - assets/images/deeptalk.png
    - assets/images/sumguy.png
    - assets/images/reportingimg.jpg
